### ISSUE TITLE
Example of layouts or partials 

### ISSUE THREAD

**Issue by pabloat81** [nest-modules/mailer#496]
Hi. I am trying the partials config.

I made it work with template only. But when i try a partial in template i have an exception of partial not found and that it needs to be registered. I configured partials options as the doc But there is no example of use! 

It is possible to use layouts? 

Thanks.

**Comment by yanarp** [comment]
Check this implementation this is what help you 

https://github.com/yanarp/nestjs-mailer

**Comment by christiaan-dockbite** [comment]
I am not seeing any usage of partials there. Can you give a more specific example?

**Comment by LaljiG** [comment]
> I am not seeing any usage of partials there. Can you give a more specific example?

hi 

did you manage to work out how to register partial in nestjs mailer  module?

**Comment by pabloat81** [comment]
No, i implemented a mailer my self finally

**Comment by yuriitaran** [comment]
It also worth saying, that in case the Mailer module can't resolve path to templates/partials, you also need to add to `nest-cli.json` the following code:
```
"compilerOptions": {
  "assets": ["*/templates/**/*.hbs"],
  "watchAssests": true
}
```

**Comment by damdafayton** [comment]
I still get the `The partial <test> could not be found`.
No matter what I did, `MailerModule` never registers the partial folder.
This block of code is ignored:
```
              options: {
                partials: {
                  dir: (() => {
                    console.log(join(__dirname, './templates'));
                    return join(__dirname, 'templates');
                  })(),
                  options: {
                    strict: true,
                  },
                },
              },
```

**Comment by bladx** [comment]
I'm facing the same issue.
I followed what @HarunOr suggested, but for some reasons the partials folder seems not to be correctly setup.
I double checked that I followed as well @yuriitaran instruction. And I do have the partials hbs files in my dist folder.

So I believe this problem is related to https://github.com/nest-modules/mailer/issues/825 but I don't know how to fix it (or at least use a workaround).

I don't know neither how to investigate/debug it.

Please note that this seems to be a Windows only issue from what I understand.

**Comment by snilesh97** [comment]
Hey @bladx @HarunOr,  I am facing the same issue did you find any fix for this?

**Comment by snilesh97** [comment]
Hey @bladx @damdafayton @HarunOr, I am facing the same issue did you find any fix for this?

**Comment by bladx** [comment]
Unfortunately no.
I'm personally not using partials, but duplicating code while it's not resolved yet.

**Comment by morgan-wild** [comment]
Are you using Nest 14?

**Comment by bladx** [comment]
Maybe I misunderstanding the question but from what I see, NestJS is only at version 9 (https://github.com/nestjs/nest/releases).
But I'm currently using v8.4.5. Do you really think upgrading to the latest version could actually solve the issue?
That might worse the effort then.

**Comment by morgan-wild** [comment]
Oh I'm sorry, I was talking about the versions of NX.

It worked for me with NX13 (nestJS Core ^8.0.0) before the migration to NX14 (which brings nestJS Core ^9.0.0 and newer nestjs packages).

I'm looking for the versions of nestjs-modules/mailer to check if it's a breaking change.

**Comment by bladx** [comment]
I'm not using NX on my project.
Here is the dependencies list I use:
```
"dependencies": {
    "@nestjs-modules/mailer": "^1.8.1",
    "@nestjs/axios": "^0.1.0",
    "@nestjs/common": "^8.4.5",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^8.4.5",
    "@nestjs/jwt": "^8.0.1",
    "@nestjs/passport": "^8.2.1",
    "@nestjs/platform-express": "^8.4.5",
    "@nestjs/swagger": "^5.2.1",
    "@nestjs/terminus": "^8.1.1",
    "@nestjs/typeorm": "^8.0.4",
    "@types/bcrypt": "^5.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "config": "^3.3.7",
    "date-fns": "^2.29.1",
    "handlebars": "^4.7.7",
    "nest-winston": "^1.7.0",
    "nodemailer": "^6.7.7",
    "passport": "^0.5.3",
    "passport-jwt": "^4.0.0",
    "pg": "^8.7.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "swagger-ui-express": "^4.5.0",
    "typeorm": "^0.2.45",
    "typeorm-naming-strategies": "^4.1.0",
    "winston": "^3.8.1",
    "winston-cloudwatch": "^6.0.1"
  }
```

**Comment by morgan-wild** [comment]
Any news? Still broken for me.

**Comment by snilesh97** [comment]
@morgan-wild hey this is working, please check your directory structure.
src/email/templates/partials/sample_1.hbs
src/email/templates/partials/sample_2.hbs



also add in  your MailerModule 
```
          options: {
            partials: {
              dir: __dirname + '/templates/partials',
              options: {
                strict: true,
              },
            },
          }
     
     
     
  ```
  
 and at last, add this in your `nest-cli.json`
 {"include": "**/*.hbs", "outDir": "./dist/src"}
 so it will come to your output directory.

**Comment by morgan-wild** [comment]
Hi I'm ok with your tip but still doesn't work

````
Error: The partial header could not be found
    at Object.invokePartial (C:\Users\mboeuf\Desktop\private\projects\beready\nx\node_modules\handlebars\lib\handlebars\runtime.js:403:11)
    at Object.invokePartialWrapper [as invokePartial] (C:\Users\mboeuf\Desktop\private\projects\beready\nx\node_modules\handlebars\lib\handlebars\runtime.js:82:39)
    at Object.eval (eval at createFunctionContext (C:\Users\mboeuf\Desktop\private\projects\beready\nx\node_modules\handlebars\lib\handlebars\compiler\javascript-compiler.js:265:23), <anonymous>:11:28)
````
    
   My configuration of NodeMailer:
   
````
    imports: [
        MailerModule.forRoot({
            transport: environment.backend.email.transport,
            template: {
                dir: path.join(__dirname, 'assets', 'templates'),
                adapter: new HandlebarsAdapter(undefined, {
                    inlineCssEnabled: true,
                    inlineCssOptions: {
                        url: ' ',
                        preserveMediaQueries: true,
                    },
                }),
                options: {
                    strict: true
                },
            },
            options: {
                partials: {
                  dir: path.join(__dirname, 'assets', 'templates', 'partials'),
                  options: {
                    strict: true,
                  },
                },
            },
            // preview: true,
        })
    ],
````

In my nest-cli.json (project.json because I'm using NX):

````
        "assets": [
          "apps/backend/src/assets", <-- That I had, all files are correctly copied to my dist folder
        ],
````
   
If I stop to use partials, it works (that the proof of my main templates are ok).

If I put my partials in the same directory of my main templates and try to use it, it crashes again.

And if I remove the options section, same result so I think it's just ignored.

**Comment by morgan-wild** [comment]
Maybe it's something wrong with my templates.

``````
<div class="wrapper">

    {{> header}}

    ....

    {{> footer}}

</div>
``````

**Comment by bladx** [comment]
I still believe that this is an issue related to the OS.
So on Windows it does not work but on other systems it does.
Your configuration seems fine, but as the logs show, you're on Windows.
I think @snilesh97 is on Mac or Linux, that's why he does not face this problem.

**Comment by snilesh97** [comment]
Yes @bladx I am using mac.

**Comment by morgan-wild** [comment]
Oh nice, I will test to run my project in a dev container (debian) or on my development environment (LXC on Debian).

**Comment by morgan-wild** [comment]
I ran my app without any modification under a devcontainer (WSL) and it **WORKS**.

So yes this issue exists but **only on Windows**.

**Comment by damdafayton** [comment]
Hi @snilesh97,

> Hey @bladx @damdafayton @HarunOr, I am facing the same issue did you find any fix for this?

I was just able to check it again today. Thanks to @bladx 's reply I was able to spot the problem easily. I have seen a similar problem in a different project which is caused by `glob.sync` not being able to parse windows paths. 

Ive opened an issue for a quick fix here: https://github.com/nest-modules/mailer/issues/906

To fix this problem on windows development server here is what you need to do:
1 -  `yarn add --dev patch-package`
2 - Add a script to `package.json` like: `"prestart:dev": "patch-package",`
3 - Add the patch in the link to folder `patches` under this name `@nestjs-modules+mailer+1.8.1.patch` -- version must match your package version.
4 - When you run `yarn start:dev` it will automatically patch.

Or you can update the changes directly into `node_modules\@nestjs-modules\mailer\dist\adapters\handlebars.adapter.js`

Since this fix is not needed on production I did all changes according to local development environment.

**Comment by Packman700** [comment]
@damdafayton Thanks a lot this working

**Comment by ezebinker** [comment]
Hi @damdafayton .

Could you explain a little more the third step ? Thank you!! 

> Hi @snilesh97,
> 
> > Hey @bladx @damdafayton @HarunOr, I am facing the same issue did you find any fix for this?
> 
> I was just able to check it again today. Thanks to @bladx 's reply I was able to spot the problem easily. I have seen a similar problem in a different project which is caused by `glob.sync` not being able to parse windows paths.
> 
> Ive opened an issue for a quick fix here: #906
> 
> To fix this problem on windows development server here is what you need to do: 1 - `yarn add --dev patch-package` 2 - Add a script to `package.json` like: `"prestart:dev": "patch-package",` 3 - Add the patch in the link to folder `patches` under this name `@nestjs-modules+mailer+1.8.1.patch` -- version must match your package version. 4 - When you run `yarn start:dev` it will automatically patch.
> 
> Or you can update the changes directly into `node_modules\@nestjs-modules\mailer\dist\adapters\handlebars.adapter.js`
> 
> Since this fix is not needed on production I did all changes according to local development environment.

**Comment by LeoCreer** [comment]
> I still believe that this is an issue related to the OS. So on Windows it does not work but on other systems it does. Your configuration seems fine, but as the logs show, you're on Windows. I think @snilesh97 is on Mac or Linux, that's why he does not face this problem.

I have this in production on a Ubuntu Server and the issue prissiest.

**Comment by syedarifiqbal** [comment]
> > > I am not seeing any usage of partials there. Can you give a more specific example?
> > 
> > 
> > hi
> > did you manage to work out how to register partial in nestjs mailer module?
> 
> @LaljiG @christiaan-dockbite If you still need this or others run into this issue: You need to add an options object with a path to your partials folder to your MailerModule like this:
> 
> ```
>         template: {
>           dir: path.join(__dirname, 'templates'),
>           adapter: new HandlebarsAdapter(),
>           options: {
>             strict: true,
>           },
>         },
>         options: {
>           partials: {
>             dir: path.join(__dirname, 'templates', 'partials'),
>             options: {
>               strict: true,
>             },
>           },
>         },
> ```
> 
> The module will automatically register the partials with their filename. My mail folder looks like this:
> 
> 📦mail ┣ 📂templates ┃ ┣ 📂partials ┃ ┃ ┣ 📜footer.hbs ┃ ┃ ┣ 📜head.hbs ┃ ┃ ┗ 📜header.hbs ┃ ┗ 📜confirmation.hbs ┣ 📜mail.module.ts ┣ 📜mail.service.spec.ts ┗ 📜mail.service.ts
> 
> In your template you can reference your partials now with their filename like this:
> 
> ```
> <body class="container">
> ...
>     <footer>
>         {{> footer}}
>     </footer>
> ...
> ```

This solution resolved the problem and saved valuable time. Previously, there was frustration and several hours spent trying to get partials to work with Nest.js Mailer. However, by configuring the partials directory using the options property, the issue was successfully addressed, and the time-consuming problem was resolved.
